apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: downstream-service
  name: downstream-service
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      run: downstream-service
  template:
    metadata:
      labels:
        run: downstream-service
    spec:
      containers:
      - image: ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}
        name: downstream-service
      terminationGracePeriodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  labels:
    run: downstream-service
  name: downstream-service-port
  namespace: default
spec:
  selector:
    run: downstream-service
  ports:
    - port: 8080
      name: http
